### ISSUE TITLE
Can it support windows or macos

### ISSUE THREAD

**Issue by yxw21** [Davincible/chromedp-undetected#2]
Hi Davincible
I made an error when compiling windows or macos. According to the error message, it seems that I am using a linux-specific field?
```
../../go/pkg/mod/github.com/!davincible/chromedp-undetected@v1.3.1/chrome.go:153:21: cmd.SysProcAttr.Pdeathsig undefined (type *syscall.SysProcAttr has no field or method Pdeathsig)
../../go/pkg/mod/github.com/!davincible/chromedp-undetected@v1.3.1/display.go:82:19: xvfb.SysProcAttr.Pdeathsig undefined (type *syscall.SysProcAttr has no field or method Pdeathsig)
```
Is there a way to be compatible with windows or macos

**Comment by Davincible** [comment]
From the readme:

> The headless option only works on linux, and requires Xvfb to be installed. Could theoretically work on Mac OS with [xquartz](https://www.xquartz.org/) but I don't have a Mac to test with, so feel free to PR.

**Comment by Davincible** [comment]
You can try to run in a docker container though

**Comment by yxw21** [comment]
I installed xquartz on macos, but the error is as follows
```
../../go/pkg/mod/github.com/!davincible/chromedp-undetected@v1.3.1/chrome.go:153:21: cmd.SysProcAttr.Pdeathsig undefined (type *syscall.SysProcAttr has no field or method Pdeathsig)
../../go/pkg/mod/github.com/!davincible/chromedp-undetected@v1.3.1/display.go:82:19: xvfb.SysProcAttr.Pdeathsig undefined (type *syscall.SysProcAttr has no field or method Pdeathsig)
```
Through the query, I learned that `Pdeathsig` is unique to linux.
So if I want to use it on windows or macos, can I only use the container?

**Comment by Davincible** [comment]
Currently yes.

I think for Mac we would have to call a different command. On Linux we call xvfb, but that comnand is not available on Mac right? So we would have to call the xquartz command

**Comment by yxw21** [comment]
After installing `xquartz` on macos, you can still call the `xvfb` command, but the compilation process cannot pass. Because you use a field `Pdeathsig` that only exists in linux. I'm not very familiar with `Pdeathsig`, so wanted to ask if you could have a compatible method.

**Comment by Davincible** [comment]
Ahhh I see. If we can change that we could perhaps make it compatible with Mac OS

**Comment by yxw21** [comment]
yes, Here is `SysProcAttr` on macos
<img width="499" alt="image" src="https://user-images.githubusercontent.com/16237562/209088902-f6f0519f-5894-49d0-97e2-cc98e7089ebb.png">

**Comment by yxw21** [comment]
You can try setting `Setpgid` field to true
```
cmd := exec.Command(command, arg...)
cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
```

**Comment by Davincible** [comment]
Could you fork the library, see if it works for you, if so PR and then I will check if it works on my end

**Comment by yxw21** [comment]
The container doesn't seem to be running successfully

Dockerfile
```
FROM chromedp/headless-shell
WORKDIR /app
RUN apt update && \
	apt install -y wget xvfb git gcc && \
	wget https://dl.google.com/go/go1.19.linux-amd64.tar.gz && \
	tar -xvf go1.19.linux-amd64.tar.gz && \
	mv go /usr/local && \
	export GOROOT=/usr/local/go && \
	export GOPATH=$HOME/go && \
	export PATH=$GOPATH/bin:$GOROOT/bin:$PATH && \
	git clone https://github.com/Davincible/chromedp-undetected.git && \
	cd chromedp-undetected && \
	go mod tidy && \
	go test
```
docker build .  -t test
<img width="618" alt="image" src="https://user-images.githubusercontent.com/16237562/209153572-71db9efa-edc9-46a8-957b-c9228f56193d.png">

**Comment by Davincible** [comment]
Don't use the chrome dp headless image, use a regular image and install chrome or chromium

**Comment by Davincible** [comment]
I've added an example `Dockerfile`
