### ISSUE TITLE
Many Core files are generated in the container

### ISSUE THREAD

**Issue by yxw21** [Davincible/chromedp-undetected#4]
# Step
- git clone https://github.com/Davincible/chromedp-undetected
- Modify the `chrome_test.go` file with the following contents
```
package chromedpundetected

import (
	"context"
	"fmt"
	"testing"
	"time"

	"github.com/chromedp/chromedp"
	"github.com/hashicorp/go-multierror"
)

var n = 3

func TestChromedpundetected(t *testing.T) {
	testRun(t,
		n,
		NewConfig(
			WithTimeout(time.Hour),
			WithHeadless(),
		),
		func(ctx context.Context) error {
			return chromedp.Run(ctx,
				chromedp.Navigate("https://nowsecure.nl"),
				chromedp.WaitVisible(`//div[@class="notfound"]`),
			)
		},
	)

	t.Logf("Undetected!")
}

func testRun(t *testing.T, n int, cfg Config, run func(ctx context.Context) error) {
	var gerr error
	var success bool

	// Attempt to run the tests multiple times, as in CI they are unstable.
	for i := 0; i < n; i++ {
		t.Logf("Attempt %d/%d", i+1, n)

		ctx, cancel, err := New(cfg)
		if err != nil {
			gerr = multierror.Append(gerr, fmt.Errorf("create context: %w", err))
			continue
		}

		if err = run(ctx); err != nil {
			gerr = multierror.Append(gerr, fmt.Errorf("chromedp run: %w", err))

			// Close Chrome instance.
			ctxN, cancelN := context.WithTimeout(ctx, time.Second*10)
			if err := chromedp.Cancel(ctxN); err != nil {
				t.Logf("failed to cancel: %v", err)
			}
			cancelN()
			cancel()

			continue
		}

		success = true
		if gerr != nil {
			t.Logf("attempt %d, errors: %s", i+1, gerr.Error())
		}

		cancel()
		break
	}

	if !success {
		t.Fatal(gerr)
	}
}
```
- Modify the Dockerfile file to run the command
```
FROM golang:1.19

RUN apt-get update && apt-get -y upgrade && apt-get -y install gcc g++ ca-certificates chromium xvfb

WORKDIR /app

COPY . .

RUN go mod download

ENTRYPOINT [ "go", "test", "-run", "TestChromedpundetected" ]
```
- Build the image and run

Wait a few minutes, then go into the container and look at it, you will see that some core files were created.

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/16237562/209692462-c64e5846-998d-42cc-9e56-54d5ae00f73a.png">

**Comment by Davincible** [comment]
I'm not sure where these are coming from. It's not something this package creates explicitly

**Comment by Davincible** [comment]
Can you check what they contain?

**Comment by yxw21** [comment]
It seems that something is crashing in chrome, I tested it with chromedp and didn't seem to find the problem. So I chose to open an issue.
<img width="863" alt="image" src="https://user-images.githubusercontent.com/16237562/209693235-8d887827-8786-4099-9e2f-d8db56ee3dfb.png">

**Comment by Davincible** [comment]
Can you try running as a different user than root, that can cause problems with Chrome

**Comment by yxw21** [comment]
After using the normal user, it seems that the core file is no longer generated, so I will close this issue for now. Thanks for your guidance.
